LIBNETCONF2_VERSION = devel
LIBNETCONF2_SITE = https://github.com/CESNET/libnetconf2.git
LIBNETCONF2_SITE_METHOD = git
LIBNETCONF2_INSTALL_STAGING = YES
LIBNETCONF2_LICENSE = BSD-3c
LIBNETCONF2_LICENSE_FILES = LICENSE
LIBNETCONF2_DEPENDENCIES = libyang libssh openssl host-pkgconf

$(eval $(cmake-package))
