NETOPEER2_SERVER_VERSION = notifications
NETOPEER2_SERVER_SITE = https://github.com/CESNET/Netopeer2.git
NETOPEER2_SERVER_SITE_METHOD = git
NETOPEER2_SERVER_SUBDIR = server
NETOPEER2_SERVER_INSTALL_STAGING = NO
NETOPEER2_SERVER_LICENSE = BSD-3c
NETOPEER2_SERVER_LICENSE_FILES = LICENSE
NETOPEER2_SERVER_DEPENDENCIES = libyang libnetconf2 sysrepo
# FIXME: enable keystored
# FIXME: enable server configuration
NETOPEER2_SERVER_CONF_OPTS = -DENABLE_CONFIGURATION=OFF

$(eval $(cmake-package))
